package ran.am.androidmanifestercodeskotlin

import android.os.Bundle
import androidx.appcompat.app.AppCompatActivity
import androidx.recyclerview.widget.LinearLayoutManager
import androidx.recyclerview.widget.RecyclerView

class ReCycleViewExpl : AppCompatActivity() {
    //int img;
    ///String re;
  //  var re: RecyclerView? = null

    lateinit var re : RecyclerView


    var arrayList: ArrayList<String>? = null
    var adapter: MyRecyclerViewAdapter? = null
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_re_cycle_view_expl)
        re = findViewById(R.id.re)
        arrayList = ArrayList()
        arrayList!!.add("bhelo")
        arrayList!!.add("dhelo")
        arrayList!!.add("ahelo")
        arrayList!!.add("ahelo")
        arrayList!!.add("ahggelo")
        arrayList!!.add("heloggas")
        arrayList!!.add("bhelo")
        arrayList!!.add("dhelo")
        arrayList!!.add("ahelo")
        arrayList!!.add("ahelo")
        arrayList!!.add("ahggelo")
        arrayList!!.add("heloggas")
        arrayList!!.add("bhelo")
        arrayList!!.add("dhelo")
        arrayList!!.add("ahelo")
        arrayList!!.add("ahelo")
        arrayList!!.add("ahggelo")
        arrayList!!.add("heloggas")
        arrayList!!.add("bhelo")
        arrayList!!.add("dhelo")
        arrayList!!.add("ahelo")
        arrayList!!.add("ahelo")
        arrayList!!.add("ahggelo")
        arrayList!!.add("heloggas")
        arrayList!!.add("bhelo")
        arrayList!!.add("dhelo")
        arrayList!!.add("ahelo")
        arrayList!!.add("ahelo")
        arrayList!!.add("ahggelo")
        arrayList!!.add("heloggas")
        arrayList!!.add("bhelo")
        arrayList!!.add("dhelo")
        arrayList!!.add("ahelo")
        arrayList!!.add("ahelo")
        arrayList!!.add("ahggelo")
        arrayList!!.add("heloggas")
        arrayList!!.add("bhelo")
        arrayList!!.add("dhelo")
        arrayList!!.add("ahelo")
        arrayList!!.add("ahelo")
        arrayList!!.add("ahggelo")
        arrayList!!.add("heloggas")
        arrayList!!.add("bhelo")
        arrayList!!.add("dhelo")
        arrayList!!.add("ahelo")
        arrayList!!.add("ahelo")
        arrayList!!.add("ahggelo")
        arrayList!!.add("heloggas")
        arrayList!!.add("bhelo")
        arrayList!!.add("dhelo")
        arrayList!!.add("ahelo")
        arrayList!!.add("ahelo")
        arrayList!!.add("ahggelo")
        arrayList!!.add("heloggas")
        arrayList!!.add("bhelo")
        arrayList!!.add("dhelo")
        arrayList!!.add("ahelo")
        arrayList!!.add("ahelo")
        arrayList!!.add("ahggelo")
        arrayList!!.add("heloggas")
        arrayList!!.add("bhelo")
        arrayList!!.add("dhelo")
        arrayList!!.add("ahelo")
        arrayList!!.add("ahelo")
        arrayList!!.add("ahggelo")
        arrayList!!.add("heloggas")
        arrayList!!.add("bhelo")
        arrayList!!.add("dhelo")
        arrayList!!.add("ahelo")
        arrayList!!.add("ahelo")
        arrayList!!.add("ahggelo")
        arrayList!!.add("heloggas")
        arrayList!!.add("bhelo")
        arrayList!!.add("dhelo")
        arrayList!!.add("ahelo")
        arrayList!!.add("ahelo")
        arrayList!!.add("ahggelo")
        arrayList!!.add("heloggas")
        arrayList!!.add("bhelo")
        arrayList!!.add("dhelo")
        arrayList!!.add("ahelo")
        arrayList!!.add("ahelo")
        arrayList!!.add("ahggelo")
        arrayList!!.add("heloggas")
        arrayList!!.add("bhelo")
        arrayList!!.add("dhelo")
        arrayList!!.add("ahelo")
        arrayList!!.add("ahelo")
        arrayList!!.add("ahggelo")
        arrayList!!.add("heloggas")
        arrayList!!.add("bhelo")
        arrayList!!.add("dhelo")
        arrayList!!.add("ahelo")
        arrayList!!.add("ahelo")
        arrayList!!.add("ahggelo")
        arrayList!!.add("heloggas")
        arrayList!!.add("bhelo")
        arrayList!!.add("dhelo")
        arrayList!!.add("ahelo")
        arrayList!!.add("ahelo")
        arrayList!!.add("ahggelo")
        arrayList!!.add("heloggas")
        arrayList!!.add("bhelo")
        arrayList!!.add("dhelo")
        arrayList!!.add("ahelo")
        arrayList!!.add("ahelo")
        arrayList!!.add("ahggelo")
        arrayList!!.add("heloggas")
        arrayList!!.add("bhelo")
        arrayList!!.add("dhelo")
        arrayList!!.add("ahelo")
        arrayList!!.add("ahelo")
        arrayList!!.add("ahggelo")
        arrayList!!.add("heloggas")
        arrayList!!.add("bhelo")
        arrayList!!.add("dhelo")
        arrayList!!.add("ahelo")
        arrayList!!.add("ahelo")
        arrayList!!.add("ahggelo")
        arrayList!!.add("heloggas")
        arrayList!!.add("bhelo")
        arrayList!!.add("dhelo")
        arrayList!!.add("ahelo")
        arrayList!!.add("ahelo")
        arrayList!!.add("ahggelo")
        arrayList!!.add("heloggas")
        arrayList!!.add("bhelo")
        arrayList!!.add("dhelo")
        arrayList!!.add("ahelo")
        arrayList!!.add("ahelo")
        arrayList!!.add("ahggelo")
        arrayList!!.add("heloggas")
        arrayList!!.add("bhelo")
        arrayList!!.add("dhelo")
        arrayList!!.add("ahelo")
        arrayList!!.add("ahelo")
        arrayList!!.add("ahggelo")
        arrayList!!.add("heloggas")
        arrayList!!.add("bhelo")
        arrayList!!.add("dhelo")
        arrayList!!.add("ahelo")
        arrayList!!.add("ahelo")
        arrayList!!.add("ahggelo")
        arrayList!!.add("heloggas")
        arrayList!!.add("bhelo")
        arrayList!!.add("dhelo")
        arrayList!!.add("ahelo")
        arrayList!!.add("ahelo")
        arrayList!!.add("ahggelo")
        arrayList!!.add("heloggas")
        arrayList!!.add("bhelo")
        arrayList!!.add("dhelo")
        arrayList!!.add("ahelo")
        arrayList!!.add("ahelo")
        arrayList!!.add("ahggelo")
        arrayList!!.add("heloggas")
        arrayList!!.add("bhelo")
        arrayList!!.add("dhelo")
        arrayList!!.add("ahelo")
        arrayList!!.add("ahelo")
        arrayList!!.add("ahggelo")
        arrayList!!.add("heloggas")
        arrayList!!.add("bhelo")
        arrayList!!.add("dhelo")
        arrayList!!.add("ahelo")
        arrayList!!.add("ahelo")
        arrayList!!.add("ahggelo")
        arrayList!!.add("heloggas")
        arrayList!!.add("bhelo")
        arrayList!!.add("dhelo")
        arrayList!!.add("ahelo")
        arrayList!!.add("ahelo")
        arrayList!!.add("ahggelo")
        arrayList!!.add("heloggas")
        arrayList!!.add("bhelo")
        arrayList!!.add("dhelo")
        arrayList!!.add("ahelo")
        arrayList!!.add("ahelo")
        arrayList!!.add("ahggelo")
        arrayList!!.add("heloggas")
        arrayList!!.add("bhelo")
        arrayList!!.add("dhelo")
        arrayList!!.add("ahelo")
        arrayList!!.add("ahelo")
        arrayList!!.add("ahggelo")
        arrayList!!.add("heloggas")
        arrayList!!.add("bhelo")
        arrayList!!.add("dhelo")
        arrayList!!.add("ahelo")
        arrayList!!.add("ahelo")
        arrayList!!.add("ahggelo")
        arrayList!!.add("heloggas")
        re.setLayoutManager(LinearLayoutManager(this@ReCycleViewExpl))
        adapter = MyRecyclerViewAdapter(this, arrayList!!)

        re.adapter= adapter

  ///      re.setAdapter(adapter)


        /*   MyListData[] myListData = new MyListData[]{
                new MyListData(re, img),
        };

        RecyclerView recyclerView = findViewById(R.id.re);
        MyListAdapter adapter = new MyListAdapter(myListData);
        recyclerView.setHasFixedSize(true);
        recyclerView.setLayoutManager(new LinearLayoutManager(this));
        recyclerView.setAdapter(adapter);
   */
    }
}